// ---------------------  AuthState
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';

export const CONFIRMACION_EXITOSA = 'CONFIRMACION_EXITOSA';
export const CONFIRMACION_ERROR = 'CONFIRMACION_ERROR';

export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const OBTENER_PERFIL = 'OBTENER_PERFIL';
export const ERROR_OBTENER_PERFIL = 'ERROR_OBTENER_PERFIL';

export const OLVIDE_PASSWORD_EXITO = 'OLVIDE_PASSWORD_EXITO';
export const OLVIDE_PASSWORD_ERROR = 'OLVIDE_PASSWORD_ERROR';

export const CAMBIO_CONTRASEÑA_EXITOSO = 'CAMBIO_CONTRASEÑA_EXITOSO';
export const CAMBIO_CONTRASEÑA_ERROR = 'CAMBIO_CONTRASEÑA_ERROR';

export const CERRAR_SESION = 'CERRAR_SESION';

export const LIMPIAR_ALERTA = 'LIMPIAR_ALERTA';

// ---------------------------- AppState

export const TOGGLE_NAV = 'TOGGLE_NAV';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const CAMBIAR_SECCION = 'CAMBIAR_SECCION';

export const OBTENER_PRODUCTOS = 'OBTENER_PRODUCTOS';
export const OBTENER_CATEGORIAS = 'OBTENER_CATEGORIAS';

export const TIPO_EDICION = 'TIPO_EDICION';

export const CATEGORIA_AGREGADA = 'CATEGORIA_AGREGADA';
export const CATEGORIA_EDITADA = 'CATEGORIA_EDITADA';
export const CATEGORIA_ELIMINADA = 'CATEGORIA_ELIMINADA';

export const PRODUCTO_ELIMINADO = 'PRODUCTO_ELIMINADO';
export const PRODUCTO_EDITADO = 'PRODUCTO_EDITADO';
export const PRODUCTO_AGREGADO = 'PRODUCTO_AGREGADO';

export const SET_CATEGORIA_FILTRO = 'SET_CATEGORIA_FILTRO';
export const ACTUALIZAR_PRODUCTOS_FILTRADOS = 'ACTUALIZAR_PRODUCTOS_FILTRADOS';

// ------------------- Registro Pedidos
export const CARGAR_CLIENTES = 'CARGAR_CLIENTES';

export const CAMBIAR_CATEGORIA_PEDIDO = 'CAMBIAR_CATEGORIA_PEDIDO';
export const LIMPIAR_CATEGORIA_PEDIDO = 'LIMPIAR_CATEGORIA_PEDIDO';

export const PRODUCTOS_FILTRADOS_PEDIDO = 'PRODUCTOS_FILTRADOS_PEDIDO';
export const AGREGAR_PRODUCTO_PEDIDO = 'AGREGAR_PRODUCTO_PEDIDO';

export const RESET_PEDIDO = 'RESET_PEDIDO';

export const AGREGA_A_PENDIENTE = 'AGREGA_A_PENDIENTE';

export const SET_PEDIDO_A_PAGAR = 'SET_PEDIDO_A_PAGAR';

export const ACTUALIZAR_PENDIENTES = 'ACTUALIZAR_PENDIENTES';

export const ACTUALIZAR_MESAS_DISPONIBLES = 'ACTUALIZAR_MESAS_DISPONIBLES';

// ------------------ Clientes

export const CLIENTE_ELIMINADO = 'CLIENTE_ELIMINADO';

export const CLIENTE_EDITADO = 'CLIENTE_EDITADO';

export const ACTUALIZAR_CLIENTES = 'ACTUALIZAR_CLIENTES';

export const SET_PEDIDOS_VER = 'SET_PEDIDOS_VER';

// ------------------ PEDIDOS

export const CARGAR_PEDIDOS = 'CARGAR_PEDIDOS';

export const PEDIDO_ELIMINADO = 'PEDIDO_ELIMINADO';


// TODO: ORGANIZAR PRODUCTOS Y CATEGORIAS...